# Generated by Django 5.2.1 on 2026-10-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentForm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
